# Azure Pipelines configuration that builds and packages the extension.
# To learn more about Azure Pipelines: https://aka.ms/learn-azure-pipelines

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: azure-pipelines-steps.yml

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure-pipelines-steps.yml
  