name: "Build"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out repository

      - uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version: "18"

      - name: "Install dependencies"
        run: npm ci
